/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/bear.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube001: THREE.Mesh
    Plane: THREE.Mesh
    Cube: THREE.Mesh
    Cube003_1: THREE.Mesh
    Cube003_2: THREE.Mesh
    Cube003: THREE.Mesh
    Cube005_1: THREE.Mesh
    Cube005_2: THREE.Mesh
    Cylinder: THREE.Mesh
    Cube005: THREE.Mesh
    Cube007: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    eye: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/bear.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials.Material} position={[0.305, 2.552, -0.665]} rotation={[-0.585, -0.197, -0.281]} scale={[0.137, 0.253, 0.276]} />
      {/* <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[-2.374, -2.011, -1.383]} scale={[1.367, 1.367, 3.097]} /> */}
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[0, 0.106, 0]} scale={[0.747, 1.288, 0.747]} />
      <group position={[0.084, 1.964, -0.01]} scale={[0.657, 0.92, 1.009]}>
        <mesh geometry={nodes.Cube003_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials['Material.002']} />
      </group>
      <mesh geometry={nodes.Cube003.geometry} material={materials.Material} position={[0, 0.916, -1.567]} rotation={[1.178, 0, 0]} scale={0.43} />
      <group position={[0.756, -0.612, -0.557]} rotation={[1.466, -0.012, 1.477]} scale={0.388}>
        <mesh geometry={nodes.Cube005_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.Cylinder.geometry} material={materials.eye} position={[0.861, 2.107, 0.193]} rotation={[0.001, -0.093, -1.298]} scale={[0.096, 0.021, 0.096]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.004']} position={[1.057, 1.931, -0.01]} rotation={[0, 0, -0.216]} scale={[0.461, 0.909, 0.352]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.004']} position={[1.073, 1.72, 0]} scale={[0.714, 1, 0.683]} />
    </group>
  )
}

useGLTF.preload('/bear.glb')
