/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/BookShelf.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Cube002: THREE.Mesh
    Cube004: THREE.Mesh
    Cube001: THREE.Mesh
    Cube003: THREE.Mesh
    Cube008_1: THREE.Mesh
    Cube008_2: THREE.Mesh
    Cube009_1: THREE.Mesh
    Cube009_2: THREE.Mesh
    Cube010_1: THREE.Mesh
    Cube010_2: THREE.Mesh
    Cube011_1: THREE.Mesh
    Cube011_2: THREE.Mesh
    Cube012: THREE.Mesh
    Cube012_1: THREE.Mesh
    Cube013: THREE.Mesh
    Cube013_1: THREE.Mesh
    Cube014: THREE.Mesh
    Cube014_1: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/BookShelf.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} scale={[2.281, 4.163, 2.389]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.Material} position={[0.037, 1.914, 0]} scale={[1.521, 0.074, 2.361]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.Material} position={[0, 0, 0.723]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Material} position={[0.037, -0.145, 0]} scale={[1.521, 0.074, 2.361]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.Material} position={[0.04, -2.282, -0.024]} scale={[1.521, 0.074, 2.361]} />
      <group position={[0.028, 2.972, 1.238]} rotation={[0, -0.799, 0]} scale={[0.461, 0.932, 0.932]}>
        <mesh geometry={nodes.Cube008_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube008_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.028, -1.3, -1.235]} rotation={[Math.PI, -0.723, Math.PI]} scale={[0.461, 0.932, 0.932]}>
        <mesh geometry={nodes.Cube009_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.028, 0.772, 1.761]} rotation={[0, 1.545, 0]} scale={[0.415, 0.932, 0.932]}>
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.028, -3.316, -1.212]} rotation={[0, 1.354, 0]} scale={[0.315, 0.932, 0.919]}>
        <mesh geometry={nodes.Cube011_1.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Cube011_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.028, -3.316, 1.041]} rotation={[0, -0.297, 0]} scale={[0.461, 0.932, 0.932]}>
        <mesh geometry={nodes.Cube012.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube012_1.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.028, 2.925, -0.272]} rotation={[0, 1.545, 0]} scale={[0.223, 0.932, 0.931]}>
        <mesh geometry={nodes.Cube013.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube013_1.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.028, 2.925, -1.404]} rotation={[0, 0.853, 0]} scale={[0.223, 0.932, 0.931]}>
        <mesh geometry={nodes.Cube014.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube014_1.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/BookShelf.glb')
