/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/KresgeBottom.glb --types 
*/
import { Html } from '@react-three/drei'

import * as THREE from 'three'
import React, { useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Cube002: THREE.Mesh
    Cube004: THREE.Mesh
    Cube006: THREE.Mesh
    Cube008: THREE.Mesh
    Cube010: THREE.Mesh
    Cube012: THREE.Mesh
    Cube014: THREE.Mesh
    Cube016: THREE.Mesh
    Cube018: THREE.Mesh
    Cube001: THREE.Mesh
    Cube003: THREE.Mesh
    Cube005: THREE.Mesh
    Cube007: THREE.Mesh
    Cube009: THREE.Mesh
    Cube011: THREE.Mesh
    Cube013: THREE.Mesh
    Cube015: THREE.Mesh
    Cube017: THREE.Mesh
    Cube019: THREE.Mesh
    Cube021: THREE.Mesh
    Cube022: THREE.Mesh
    Cube024: THREE.Mesh
    Cube025: THREE.Mesh
    Cube029: THREE.Mesh
    Cube030: THREE.Mesh
    Cube031: THREE.Mesh
    Cube032: THREE.Mesh
    Cube033: THREE.Mesh
    Cube034: THREE.Mesh
    Cube020: THREE.Mesh
    Cube023: THREE.Mesh
    Cube026: THREE.Mesh
    Cube027: THREE.Mesh
    Cube028: THREE.Mesh
    Cube035: THREE.Mesh
    Cube036: THREE.Mesh
    Cube038: THREE.Mesh
    Cube040: THREE.Mesh
    Cube042: THREE.Mesh
    Cube037: THREE.Mesh
    Cube039: THREE.Mesh
    Cube041: THREE.Mesh
    Cube043: THREE.Mesh
    Cube044: THREE.Mesh
    Cube046: THREE.Mesh
    Cube045: THREE.Mesh
    Cube047: THREE.Mesh
    Cube048: THREE.Mesh
    Cube049: THREE.Mesh
    Cube050: THREE.Mesh
    Cube051: THREE.Mesh
    Cube052: THREE.Mesh
    Cube053: THREE.Mesh
    Cube054: THREE.Mesh
    Cube055: THREE.Mesh
    Cube056: THREE.Mesh
    Cube057: THREE.Mesh
    Cube058: THREE.Mesh
    Cube059: THREE.Mesh
    Cube060: THREE.Mesh
    Cube061: THREE.Mesh
    Cube062: THREE.Mesh
    Cube063: THREE.Mesh
    Cube064: THREE.Mesh
    Cube065: THREE.Mesh
    Cube066: THREE.Mesh
    Cube067: THREE.Mesh
    Cube068: THREE.Mesh
    Cube069: THREE.Mesh
    Cube070: THREE.Mesh
    Cube071: THREE.Mesh
    Cube072: THREE.Mesh
    Cube073: THREE.Mesh
    Cube074: THREE.Mesh
    Cube075: THREE.Mesh
    Cube076: THREE.Mesh
    Cube077: THREE.Mesh
    Cube078: THREE.Mesh
    Cube079: THREE.Mesh
    Cube080: THREE.Mesh
    Cube081: THREE.Mesh
    Cube082: THREE.Mesh
    Cube083: THREE.Mesh
    Cube084: THREE.Mesh
    Cube085: THREE.Mesh
    Cube086: THREE.Mesh
    Cube087: THREE.Mesh
    Cube088: THREE.Mesh
    Cube089: THREE.Mesh
    Cube090: THREE.Mesh
    Cube091: THREE.Mesh
    Cube092: THREE.Mesh
    Cube093: THREE.Mesh
    Cube094: THREE.Mesh
    Cube095: THREE.Mesh
    Cube096: THREE.Mesh
    Cube097: THREE.Mesh
    Cube098: THREE.Mesh
    Cube099: THREE.Mesh
    Cube100: THREE.Mesh
    Cube101: THREE.Mesh
    Cube102: THREE.Mesh
    Cube103: THREE.Mesh
    Cube104: THREE.Mesh
    Cube105: THREE.Mesh
    Cube106: THREE.Mesh
    Cube107: THREE.Mesh
    Cube108: THREE.Mesh
    Cube109: THREE.Mesh
    Cube110: THREE.Mesh
    Cube111: THREE.Mesh
    Cube112: THREE.Mesh
    Cube113: THREE.Mesh
  }
  materials: {
    Table: THREE.MeshStandardMaterial
    Chair: THREE.MeshStandardMaterial
    Couch: THREE.MeshStandardMaterial
    Shelf: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}
interface ModelProps extends React.ComponentProps<'group'> {
  opacity?: number
  transparent?: boolean
}
const DialogLabel = () => {  
  return (
    <Html 
      position={[0, 1.5, 0]} // Offsets label to float above the mesh
      center 
      distanceFactor={15} // Makes label shrink/grow with distance (optional)
      occlude // Hides label when object is behind a wall (optional)
    >
      <div style={{
        background: 'white',
        padding: '6px 10px',
        borderRadius: '8px',
        fontSize: '24px',
        fontFamily: 'sans-serif',
        fontWeight: 'bold',
        boxShadow: '0 2px 4px rgba(0,0,0,0.2)',
        whiteSpace: 'nowrap',
        pointerEvents: 'none' // Allows clicking "through" the label
      }}>
        Printers
      </div>
    </Html>
  )
}
export function Model({ opacity = 1, transparent = false, ...props }: ModelProps) {
  const { nodes, materials } = useGLTF('/models/KresgeBottom.glb') as GLTFResult
  const m = useMemo(() => {
    // Helper function to clone a material and apply the props
    const applyState = (material: THREE.MeshStandardMaterial) => {
      const clone = material.clone()
      clone.transparent = transparent || opacity < 1
      clone.opacity = opacity
      // Preserves the original color/texture map
      return clone
    }

    return {
      Table: applyState(materials.Table),
      Chair: applyState(materials.Chair),
      Couch: applyState(materials.Couch),
      Shelf: applyState(materials.Shelf)
    }
  }, [materials, opacity, transparent])
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={m.Table} position={[6.527, 0, -5.555]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube002.geometry} material={m.Table} position={[8.245, 0, -5.555]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube004.geometry} material={m.Table} position={[6.527, 0, -7.268]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube006.geometry} material={m.Table} position={[8.245, 0, -7.268]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube008.geometry} material={m.Table} position={[6.527, 0, -8.856]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube010.geometry} material={m.Table} position={[8.245, 0, -8.856]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube012.geometry} material={m.Table} position={[5.849, 0, -13.672]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube014.geometry} material={m.Table} position={[7.568, 0, -13.672]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube016.geometry} material={m.Table} position={[5.849, 0, -15.261]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube018.geometry} material={m.Table} position={[7.568, 0, -15.261]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube001.geometry} material={m.Chair} position={[6.21, 0, -6.086]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube003.geometry} material={m.Chair} position={[7.929, 0, -6.086]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube005.geometry} material={m.Chair} position={[6.21, 0, -7.798]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube007.geometry} material={m.Chair} position={[7.929, 0, -7.798]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube009.geometry} material={m.Chair} position={[6.21, 0, -9.387]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube011.geometry} material={m.Chair} position={[7.929, 0, -9.387]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube013.geometry} material={m.Chair} position={[5.533, 0, -14.203]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube015.geometry} material={m.Chair} position={[7.251, 0, -14.203]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube017.geometry} material={m.Chair} position={[5.533, 0, -15.791]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube019.geometry} material={m.Chair} position={[7.251, 0, -15.791]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube021.geometry} material={m.Chair} position={[2.86, 2.327, -6.997]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube022.geometry} material={m.Chair} position={[2.388, 2.327, -6.997]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube024.geometry} material={m.Chair} position={[2.86, 2.327, -9.072]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube025.geometry} material={m.Chair} position={[2.388, 2.327, -9.072]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube029.geometry} material={m.Chair} position={[2.86, 2.327, -4.979]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube030.geometry} material={m.Chair} position={[2.388, 2.327, -4.979]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube031.geometry} material={m.Chair} position={[2.014, 2.327, -10.025]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube032.geometry} material={m.Chair} position={[2.524, 2.327, -10.025]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube033.geometry} material={m.Chair} position={[3.111, 2.327, -10.025]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube034.geometry} material={m.Chair} position={[3.621, 2.327, -10.025]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube020.geometry} material={m.Table} position={[3.176, 2.327, -6.466]} scale={[1.096, 1, 0.391]} ><DialogLabel/></mesh>
        
      <mesh geometry={nodes.Cube023.geometry} material={m.Table} position={[3.176, 2.327, -8.542]} scale={[1.096, 1, 0.391]} />
      <mesh geometry={nodes.Cube026.geometry} material={m.Chair} position={[2.86, 2.9, -8.732]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube027.geometry} material={m.Chair} position={[2.388, 2.9, -8.732]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube028.geometry} material={m.Table} position={[3.176, 2.327, -4.449]} scale={[1.096, 1, 0.391]} />
      <mesh geometry={nodes.Cube035.geometry} material={nodes.Cube035.material} position={[6.052, -0.028, -11.323]} scale={[1, 1, 0.891]} />
      <mesh geometry={nodes.Cube036.geometry} material={m.Table} position={[10.45, 0, -20.458]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube038.geometry} material={m.Table} position={[12.168, 0, -20.458]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube040.geometry} material={m.Table} position={[10.45, 0, -22.047]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube042.geometry} material={m.Table} position={[12.168, 0, -22.047]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube037.geometry} material={m.Chair} position={[10.134, 0, -20.989]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube039.geometry} material={m.Chair} position={[11.852, 0, -20.989]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube041.geometry} material={m.Chair} position={[10.134, 0, -22.578]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube043.geometry} material={m.Chair} position={[11.852, 0, -22.578]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube044.geometry} material={m.Table} position={[14.107, 0, -20.458]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube046.geometry} material={m.Table} position={[14.107, 0, -22.047]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube045.geometry} material={m.Chair} position={[13.791, 0, -20.989]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube047.geometry} material={m.Chair} position={[13.791, 0, -22.578]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube048.geometry} material={m.Table} position={[17.257, 0, -10.148]} scale={[1.432, 1, 0.391]} />
      <mesh geometry={nodes.Cube049.geometry} material={m.Chair} position={[16.773, 0, -10.679]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube050.geometry} material={m.Chair} position={[16.232, 0, -10.679]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube051.geometry} material={m.Chair} position={[17.827, 0, -10.679]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube052.geometry} material={m.Chair} position={[17.285, 0, -10.679]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube053.geometry} material={m.Chair} position={[18.358, 0, -10.679]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube054.geometry} material={m.Table} position={[17.257, 0, -11.736]} scale={[1.432, 1, 0.391]} />
      <mesh geometry={nodes.Cube055.geometry} material={m.Chair} position={[16.773, 0, -12.267]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube056.geometry} material={m.Chair} position={[16.232, 0, -12.267]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube057.geometry} material={m.Chair} position={[17.827, 0, -12.267]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube058.geometry} material={m.Chair} position={[17.285, 0, -12.267]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube059.geometry} material={m.Chair} position={[18.358, 0, -12.267]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube060.geometry} material={m.Table} position={[17.257, 0, -13.331]} scale={[1.432, 1, 0.391]} />
      <mesh geometry={nodes.Cube061.geometry} material={m.Chair} position={[16.773, 0, -13.862]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube062.geometry} material={m.Chair} position={[16.232, 0, -13.862]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube063.geometry} material={m.Chair} position={[17.827, 0, -13.862]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube064.geometry} material={m.Chair} position={[17.285, 0, -13.862]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube065.geometry} material={m.Chair} position={[18.358, 0, -13.862]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube066.geometry} material={m.Table} position={[17.257, 0, -14.932]} scale={[1.432, 1, 0.391]} />
      <mesh geometry={nodes.Cube067.geometry} material={m.Chair} position={[16.773, 0, -15.462]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube068.geometry} material={m.Chair} position={[16.232, 0, -15.462]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube069.geometry} material={m.Chair} position={[17.827, 0, -15.462]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube070.geometry} material={m.Chair} position={[17.285, 0, -15.462]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube071.geometry} material={m.Chair} position={[18.358, 0, -15.462]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube072.geometry} material={m.Table} position={[17.257, 0, -16.514]} scale={[1.432, 1, 0.391]} />
      <mesh geometry={nodes.Cube073.geometry} material={m.Chair} position={[16.773, 0, -17.045]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube074.geometry} material={m.Chair} position={[16.232, 0, -17.045]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube075.geometry} material={m.Chair} position={[17.827, 0, -17.045]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube076.geometry} material={m.Chair} position={[17.285, 0, -17.045]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube077.geometry} material={m.Chair} position={[18.358, 0, -17.045]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube078.geometry} material={m.Table} position={[2.839, 1.535, -13.247]} scale={[0.506, 0.615, 0.241]} />
      <mesh geometry={nodes.Cube079.geometry} material={m.Table} position={[2.461, 1.535, -15.361]} rotation={[0, Math.PI / 2, 0]} scale={[0.506, 0.615, 0.241]} />
      <mesh geometry={nodes.Cube080.geometry} material={m.Table} position={[1.693, 1.535, -16.306]} rotation={[0, Math.PI / 2, 0]} scale={[0.282, 0.615, 0.241]} />
      <mesh geometry={nodes.Cube081.geometry} material={m.Couch} position={[2.354, 1.535, -16.306]} rotation={[0, Math.PI / 2, 0]} scale={[0.282, 0.615, 0.334]} />
      <mesh geometry={nodes.Cube082.geometry} material={m.Couch} position={[3.116, 1.535, -16.306]} rotation={[0, Math.PI / 2, 0]} scale={[0.282, 0.615, 0.334]} />
      <mesh geometry={nodes.Cube083.geometry} material={m.Couch} position={[1.787, 1.535, -13.294]} rotation={[Math.PI, 0, Math.PI]} scale={[0.282, 0.615, 0.334]} />
      <mesh geometry={nodes.Cube084.geometry} material={m.Couch} position={[1.787, 1.535, -14.174]} rotation={[Math.PI, 0, Math.PI]} scale={[0.282, 0.615, 0.334]} />
      <mesh geometry={nodes.Cube085.geometry} material={m.Table} position={[1.693, 1.535, -12.609]} rotation={[0, Math.PI / 2, 0]} scale={[0.282, 0.615, 0.241]} />
      <mesh geometry={nodes.Cube086.geometry} material={m.Couch} position={[2.803, 1.535, -12.573]} rotation={[0, Math.PI / 2, 0]} scale={[0.282, 0.615, 0.797]} />
      <mesh geometry={nodes.Cube087.geometry} material={m.Couch} position={[1.735, 1.535, -15.361]} rotation={[Math.PI, 0, Math.PI]} scale={[0.282, 0.615, 0.52]} />
      <mesh geometry={nodes.Cube088.geometry} material={m.Shelf} position={[12.211, 0.985, -8.248]} scale={[2.122, 1, 0.133]} />
      <mesh geometry={nodes.Cube089.geometry} material={m.Shelf} position={[12.211, 0.985, -9.112]} scale={[2.122, 1, 0.133]} />
      <mesh geometry={nodes.Cube090.geometry} material={m.Shelf} position={[12.211, 0.985, -9.962]} scale={[2.122, 1, 0.133]} />
      <mesh geometry={nodes.Cube091.geometry} material={m.Shelf} position={[12.211, 0.985, -10.8]} scale={[2.122, 1, 0.133]} />
      <mesh geometry={nodes.Cube092.geometry} material={m.Shelf} position={[12.211, 0.985, -11.622]} scale={[2.122, 1, 0.133]} />
      <mesh geometry={nodes.Cube093.geometry} material={m.Shelf} position={[12.211, 0.985, -12.486]} scale={[2.122, 1, 0.133]} />
      <mesh geometry={nodes.Cube094.geometry} material={m.Shelf} position={[12.211, 0.985, -13.337]} scale={[2.122, 1, 0.133]} />
      <mesh geometry={nodes.Cube095.geometry} material={m.Shelf} position={[12.211, 0.985, -14.174]} scale={[2.122, 1, 0.133]} />
      <mesh geometry={nodes.Cube096.geometry} material={m.Shelf} position={[12.211, 0.985, -15.009]} scale={[2.122, 1, 0.133]} />
      <mesh geometry={nodes.Cube097.geometry} material={m.Shelf} position={[12.211, 0.985, -15.874]} scale={[2.122, 1, 0.133]} />
      <mesh geometry={nodes.Cube098.geometry} material={m.Shelf} position={[12.211, 0.985, -16.724]} scale={[2.122, 1, 0.133]} />
      <mesh geometry={nodes.Cube099.geometry} material={m.Shelf} position={[12.211, 0.985, -17.562]} scale={[2.122, 1, 0.133]} />
      <mesh geometry={nodes.Cube100.geometry} material={m.Shelf} position={[12.211, 0.985, -18.361]} scale={[2.122, 1, 0.133]} />
      <mesh geometry={nodes.Cube101.geometry} material={m.Shelf} position={[12.211, 0.985, -19.198]} scale={[2.122, 1, 0.133]} />
      <mesh geometry={nodes.Cube102.geometry} material={m.Shelf} position={[17.052, 0.985, -18.36]} scale={[1.583, 1, 0.133]} />
      <mesh geometry={nodes.Cube103.geometry} material={m.Shelf} position={[17.052, 0.985, -19.195]} scale={[1.583, 1, 0.133]} />
      <mesh geometry={nodes.Cube104.geometry} material={m.Shelf} position={[17.052, 0.985, -20.06]} scale={[1.583, 1, 0.133]} />
      <mesh geometry={nodes.Cube105.geometry} material={m.Shelf} position={[17.052, 0.985, -20.91]} scale={[1.583, 1, 0.133]} />
      <mesh geometry={nodes.Cube106.geometry} material={m.Shelf} position={[17.052, 0.985, -21.748]} scale={[1.583, 1, 0.133]} />
      <mesh geometry={nodes.Cube107.geometry} material={m.Shelf} position={[17.052, 0.985, -22.547]} scale={[1.583, 1, 0.133]} />
      <mesh geometry={nodes.Cube108.geometry} material={m.Shelf} position={[17.052, 0.985, -4.039]} scale={[1.583, 1, 0.133]} />
      <mesh geometry={nodes.Cube109.geometry} material={m.Shelf} position={[17.052, 0.985, -4.874]} scale={[1.583, 1, 0.133]} />
      <mesh geometry={nodes.Cube110.geometry} material={m.Shelf} position={[17.052, 0.985, -5.739]} scale={[1.583, 1, 0.133]} />
      <mesh geometry={nodes.Cube111.geometry} material={m.Shelf} position={[17.052, 0.985, -6.589]} scale={[1.583, 1, 0.133]} />
      <mesh geometry={nodes.Cube112.geometry} material={m.Shelf} position={[17.052, 0.985, -7.427]} scale={[1.583, 1, 0.133]} />
      <mesh geometry={nodes.Cube113.geometry} material={m.Shelf} position={[17.052, 0.985, -8.226]} scale={[1.583, 1, 0.133]} />
    </group>
  )
}

useGLTF.preload('/KresgeBottom.glb')
