/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/KresgeTop.glb --types 
*/
import { Html } from '@react-three/drei'
import * as THREE from 'three'
import React, { useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube114: THREE.Mesh
    Cube115: THREE.Mesh
    Cube116: THREE.Mesh
    Cube117: THREE.Mesh
    Cube118: THREE.Mesh
    Cube119: THREE.Mesh
    Cube120: THREE.Mesh
    Cube121: THREE.Mesh
    Cube122: THREE.Mesh
    Cube123: THREE.Mesh
    Cube124: THREE.Mesh
    Cube125: THREE.Mesh
    Cube126: THREE.Mesh
    Cube127: THREE.Mesh
    Cube128: THREE.Mesh
    Cube129: THREE.Mesh
    Cube130: THREE.Mesh
    Cube131: THREE.Mesh
    Cube132: THREE.Mesh
    Cube133: THREE.Mesh
    Cube134: THREE.Mesh
    Cube135: THREE.Mesh
    Cube136: THREE.Mesh
    Cube137: THREE.Mesh
    Cube138: THREE.Mesh
    Cube139: THREE.Mesh
    Cube140: THREE.Mesh
    Cube141: THREE.Mesh
    Cube142: THREE.Mesh
    Cube143: THREE.Mesh
    Cube144: THREE.Mesh
    Cube145: THREE.Mesh
    Cube146: THREE.Mesh
    Cube147: THREE.Mesh
    Cube148: THREE.Mesh
    Cube149: THREE.Mesh
    Cube150: THREE.Mesh
    Cube151: THREE.Mesh
    Cube152: THREE.Mesh
    Cube153: THREE.Mesh
    Cube154: THREE.Mesh
    Cube155: THREE.Mesh
    Cube156: THREE.Mesh
    Cube157: THREE.Mesh
    Cube158: THREE.Mesh
    Cube159: THREE.Mesh
    Cube160: THREE.Mesh
    Cube161: THREE.Mesh
    Cube162: THREE.Mesh
    Cube163: THREE.Mesh
    Cube164: THREE.Mesh
    Cube165: THREE.Mesh
    Cube166: THREE.Mesh
  }
  materials: {
    Table: THREE.MeshStandardMaterial
    Chair: THREE.MeshStandardMaterial
    Room: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}
interface ModelProps extends React.ComponentProps<'group'> {
  opacity?: number
  transparent?: boolean
}
const DialogLabel = () => {
  const time = useMemo(() => Math.floor(Math.random() * 6) + 4, [])
  
  return (
    <Html 
      position={[0, 1.5, 0]} // Offsets label to float above the mesh
      center 
      distanceFactor={15} // Makes label shrink/grow with distance (optional)
      occlude // Hides label when object is behind a wall (optional)
    >
      <div style={{
        background: 'white',
        padding: '6px 10px',
        borderRadius: '8px',
        fontSize: '24px',
        fontFamily: 'sans-serif',
        fontWeight: 'bold',
        boxShadow: '0 2px 4px rgba(0,0,0,0.2)',
        whiteSpace: 'nowrap',
        pointerEvents: 'none' // Allows clicking "through" the label
      }}>
        Next available at {time}pm
      </div>
    </Html>
  )
}
export function Model({ opacity = 1, transparent = false, ...props }: ModelProps) {
  const { nodes, materials } = useGLTF('/models/KresgeTop.glb') as GLTFResult
  const m = useMemo(() => {
    // Helper function to clone a material and apply the props
    const applyState = (material: THREE.MeshStandardMaterial) => {
      const clone = material.clone()
      clone.transparent = transparent || opacity < 1
      clone.opacity = opacity
      // Preserves the original color/texture map
      return clone
    }

    return {
      Table: applyState(materials.Table),
      Chair: applyState(materials.Chair),
      Room: applyState(materials.Room)
    }
  }, [materials, opacity, transparent])
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube114.geometry} material={m.Table} position={[13.648, 4.557, -10.073]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube115.geometry} material={m.Chair} position={[13.332, 4.557, -10.604]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube116.geometry} material={m.Table} position={[13.648, 4.557, -11.801]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube117.geometry} material={m.Chair} position={[13.332, 4.557, -12.332]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube118.geometry} material={m.Table} position={[13.648, 4.557, -13.723]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube119.geometry} material={m.Chair} position={[13.332, 4.557, -14.254]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube120.geometry} material={m.Table} position={[13.648, 4.557, -15.452]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube121.geometry} material={m.Chair} position={[13.332, 4.557, -15.982]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube122.geometry} material={m.Table} position={[11.232, 4.557, -10.073]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube123.geometry} material={m.Chair} position={[10.916, 4.557, -10.604]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube124.geometry} material={m.Table} position={[11.232, 4.557, -11.801]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube125.geometry} material={m.Chair} position={[10.916, 4.557, -12.332]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube126.geometry} material={m.Table} position={[11.232, 4.557, -13.723]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube127.geometry} material={m.Chair} position={[10.916, 4.557, -14.254]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube128.geometry} material={m.Table} position={[11.232, 4.557, -15.452]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube129.geometry} material={m.Chair} position={[10.916, 4.557, -15.982]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube130.geometry} material={m.Table} position={[4.672, 4.557, -22.647]} rotation={[0, Math.PI / 2, 0]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube131.geometry} material={m.Chair} position={[4.141, 4.557, -22.33]} rotation={[0, Math.PI / 2, 0]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube132.geometry} material={m.Table} position={[-0.461, 4.557, -22.647]} rotation={[0, Math.PI / 2, 0]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube133.geometry} material={m.Chair} position={[-0.992, 4.557, -22.33]} rotation={[0, Math.PI / 2, 0]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube134.geometry} material={m.Table} position={[11.232, 4.557, -6.564]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube135.geometry} material={m.Chair} position={[10.916, 4.557, -7.094]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube136.geometry} material={m.Table} position={[11.232, 4.557, -8.292]} scale={[0.64, 1, 0.391]} />
      <mesh geometry={nodes.Cube137.geometry} material={m.Chair} position={[10.916, 4.557, -8.823]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube138.geometry} material={m.Table} position={[-0.339, 4.557, -17.942]} rotation={[0, Math.PI / 2, 0]} scale={[0.29, 1, 0.391]} />
      <mesh geometry={nodes.Cube139.geometry} material={m.Chair} position={[-0.869, 4.557, -17.932]} rotation={[0, Math.PI / 2, 0]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube140.geometry} material={m.Table} position={[-2.033, 4.557, -17.942]} rotation={[0, Math.PI / 2, 0]} scale={[0.29, 1, 0.391]} />
      <mesh geometry={nodes.Cube141.geometry} material={m.Chair} position={[-2.564, 4.557, -17.932]} rotation={[0, Math.PI / 2, 0]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube142.geometry} material={m.Table} position={[3.039, 4.557, -17.942]} rotation={[0, Math.PI / 2, 0]} scale={[0.29, 1, 0.391]} />
      <mesh geometry={nodes.Cube143.geometry} material={m.Chair} position={[2.509, 4.557, -17.932]} rotation={[0, Math.PI / 2, 0]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube144.geometry} material={m.Table} position={[1.345, 4.557, -17.942]} rotation={[0, Math.PI / 2, 0]} scale={[0.29, 1, 0.391]} />
      <mesh geometry={nodes.Cube145.geometry} material={m.Chair} position={[0.815, 4.557, -17.932]} rotation={[0, Math.PI / 2, 0]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube146.geometry} material={m.Table} position={[6.34, 4.557, -17.942]} rotation={[0, Math.PI / 2, 0]} scale={[0.29, 1, 0.391]} />
      <mesh geometry={nodes.Cube147.geometry} material={m.Chair} position={[5.81, 4.557, -17.932]} rotation={[0, Math.PI / 2, 0]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube148.geometry} material={m.Table} position={[4.73, 4.557, -17.942]} rotation={[0, Math.PI / 2, 0]} scale={[0.29, 1, 0.391]} />
      <mesh geometry={nodes.Cube149.geometry} material={m.Chair} position={[4.199, 4.557, -17.932]} rotation={[0, Math.PI / 2, 0]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube150.geometry} material={m.Table} position={[8.082, 4.557, -17.942]} rotation={[0, Math.PI / 2, 0]} scale={[0.29, 1, 0.391]} />
      <mesh geometry={nodes.Cube151.geometry} material={m.Chair} position={[7.552, 4.557, -17.932]} rotation={[0, Math.PI / 2, 0]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube152.geometry} material={m.Room} position={[13.438, 4.782, -5.731]} scale={[1.416, 1, 1]} ><DialogLabel />
      </mesh>
      <mesh geometry={nodes.Cube153.geometry} material={m.Room} position={[18.191, 4.782, -4.604]} scale={[1.416, 1, 2.161]} ><DialogLabel />
      </mesh>
      <mesh geometry={nodes.Cube154.geometry} material={m.Table} position={[17.013, 4.557, -7.003]} scale={[0.351, 1, 0.213]} />
      <mesh geometry={nodes.Cube155.geometry} material={m.Chair} position={[16.998, 4.557, -7.353]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube156.geometry} material={m.Table} position={[17.786, 4.557, -7.003]} scale={[0.351, 1, 0.213]} />
      <mesh geometry={nodes.Cube157.geometry} material={m.Chair} position={[17.771, 4.557, -7.353]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube158.geometry} material={m.Table} position={[18.536, 4.557, -7.003]} scale={[0.351, 1, 0.213]} />
      <mesh geometry={nodes.Cube159.geometry} material={m.Chair} position={[18.521, 4.557, -7.353]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube160.geometry} material={m.Table} position={[19.31, 4.557, -7.003]} scale={[0.351, 1, 0.213]} />
      <mesh geometry={nodes.Cube161.geometry} material={m.Chair} position={[19.295, 4.557, -7.353]} scale={[0.168, 1, 0.113]} />
      <mesh geometry={nodes.Cube162.geometry} material={m.Room} position={[16.801, 4.555, -18.975]} scale={[1.416, 1, 2.161]} >
      <DialogLabel />
      </mesh>
      <mesh geometry={nodes.Cube163.geometry} material={m.Room} position={[5.86, 4.782, -20.045]} scale={[1.416, 1, 1]} ><DialogLabel />
      </mesh>
      <mesh geometry={nodes.Cube164.geometry} material={m.Room} position={[1.175, 4.782, -20.045]} scale={[1.416, 1, 1]} ><DialogLabel />
      </mesh>
      <mesh geometry={nodes.Cube165.geometry} material={m.Room} position={[1.175, 4.782, -20.045]} scale={[1.416, 1, 1]} ><DialogLabel />
      </mesh>
      <mesh geometry={nodes.Cube166.geometry} material={nodes.Cube166.material} position={[6.052, -0.028, -11.323]} scale={[1, 1, 0.891]} />
    </group>
  )
}

useGLTF.preload('/KresgeTop.glb')
